FROM node:21-alpine3.18

WORKDIR /app

COPY package.json tsconfig.json .npmrc ./
COPY src ./src
COPY tools ./tools
RUN ls -a
RUN npm cache clean --force
RUN npm install 
RUN npm install -g nodemon
RUN npm config list
EXPOSE 4000

CMD [ "npm","run","dev" ]

