FROM node:14-alpine3.14

WORKDIR /app
# Install curl
RUN apk add --no-cache curl
COPY package.json tsconfig.json .npmrc ./
COPY src ./src

RUN ls -a
RUN npm cache clean --force
RUN curl -v https://registry.npmjs.org

RUN npm config set registry https://registry.npmjs.org/
RUN npm install 
RUN npm install -g nodemon
RUN npm config list
EXPOSE 4000

CMD [ "npm","run","dev" ]

